#!/bin/bash
echo "=============================Enter installazition================="

//install database
yum -y install mariadb-server mariadb

//install develop tools
yum groupinstall 'Development Tools'
yum install python-dev
yum install jemalloc-devel


//install  redis-server
wget http://download.redis.io/redis-stable.tar.gz
tar xvzf redis-stable.tar.gz
cd redis-stable
make
./src/redis-server



//install python-pip
cd ..
sudo yum install epel-release
sudo yum install python-pip

//install redis client moudle
sudo pip install redis


//start ivp service
echo $(pwd)
systemctl start mariadb
redis-server
echo "what is ------------------------------>"
//python encoder.py
//python decoder.py


























